version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./latex:/latex
    env_file:
      - .env
