export default
	{
		title: "Is Stadia Worth Building?",
		term: {
			season: "Fall",
			year: "2022",
			workTermNumber: "3"
		},
		company: {
			name: "Google",
			position: "Developer",
			location: "Victoria, BC, Canada",
		},
		student: {
			name: "Rui Ueyama",
			number: "V00389870",
			discipline: "Software Engineering",
			email: "rui314@uvic.ca",
			address: "1392 Allegro Royal Lane",
			city: "Edmonton",
			province: "Alberta",
			zip: "A0M 1S2"
		},
		dueDate: "April 24th, 2022",
		marker: {
			name: "Kevin Hall",
			address: "1392 Allegro Royal Lane",
			city: "Victoria",
			province: "BC",
			zip: "H0H 0H0"
		},
		ai: {
			transmittal: "Generated by GPT-3",
			summary: "Generated by GPT-3",
			introduction: "Generated by GPT-3",
			discussion: [
				{ theme: "thing 1", content: "..." },
				{ theme: "thing 2", content: "..." },
				{ theme: "thing 3", content: "..." },
			],
			discussionIntro: "Generated by GPT-3",
			conclusion: "Generated by GPT-3",
			recommendation: "Generated by GPT-3",
		}
	}
