export interface TemplateInput {
    title:   string;
    term:    Term;
    company: Company;
    student: Student;
    dueDate: string;
    marker:  Marker;
    ai:      AI;
}

export interface APIInput {
    title:     string;
    term:      Term;
    company:   Company;
    student:   Student;
    dueDate:   string;
    marker:    Marker;
    project:   string;
    problem:   string;
    solutions: string[];
}

export interface AI {
    letter:          string;
    summary:         string;
    introduction:    string;
    background:      string;
    discussion:      Discussion[];
    discussionIntro: string;
    conclusion:      string;
    recommendation:  string;
}

export interface Discussion {
    theme:   string;
    content: string;
}

export interface Company {
    name:     string;
    position: string;
    location: string;
}

export interface Marker {
    name:     string;
    address:  string;
    city:     string;
    province: string;
    zip:      string;
}

export interface Student {
    name:       string;
    number:     string;
    discipline: string;
    email:      string;
    address:    string;
    city:       string;
    province:   string;
    zip:        string;
}

export interface Term {
    season:         string;
    year:           string;
    workTermNumber: string;
}



const template: TemplateInput =
{
	title: "Is Stadia Worth Building?",
	term: {
		season: "Fall",
		year: "2022",
		workTermNumber: "3"
	},
	company: {
		name: "Google",
		position: "Developer",
		location: "Victoria, BC, Canada",
	},
	student: {
		name: "Rui Ueyama",
		number: "V00389870",
		discipline: "Software Engineering",
		email: "rui314@uvic.ca",
		address: "1392 Allegro Royal Lane",
		city: "Edmonton",
		province: "Alberta",
		zip: "A0M 1S2"
	},
	dueDate: "April 24th, 2022",
	marker: {
		name: "Kevin Hall",
		address: "1392 Allegro Royal Lane",
		city: "Victoria",
		province: "BC",
		zip: "H0H 0H0"
	},
	ai: {
		letter: "Generated by GPT-3",
		summary: "Generated by GPT-3",
		introduction: "Generated by GPT-3",
		background: "Generated by GPT-3",
		discussion: [
			{ theme: "thing 1", content: "thing 1 content"},
			{ theme: "thing 2", content: "thing 2 content"},
			{ theme: "thing 3", content: "thing 3 content"},
		],
		discussionIntro: "Generated by GPT-3",
		conclusion: "Generated by GPT-3",
		recommendation: "Generated by GPT-3",
	}
}

const frontend: APIInput =
{
	title: "Is Stadia Worth Building?",
	term: {
		season: "Fall",
		year: "2022",
		workTermNumber: "3"
	},
	company: {
		name: "Google",
		position: "Developer",
		location: "Victoria, BC, Canada",
	},
	student: {
		name: "Rui Ueyama",
		number: "V00389870",
		discipline: "Software Engineering",
		email: "rui314@uvic.ca",
		address: "1392 Allegro Royal Lane",
		city: "Edmonton",
		province: "Alberta",
		zip: "A0M 1S2"
	},
	dueDate: "April 24th, 2022",
	marker: {
		name: "Kevin Hall",
		address: "1392 Allegro Royal Lane",
		city: "Victoria",
		province: "BC",
		zip: "H0H 0H0"
	},
	project: "cloud-based video gaming service",
	problem: "Stadia has too much network latency",
	solutions: [
		"move gaming to local machine",
		"research new network quality of service algorithms",
		"stick to turn based games",
	]
}

export {
	frontend,
	template,
}